package frc.team3223.robot2016;

public enum HighGoalStates {
  START,
  DRIVING_BACKWARDS,
  CALCULATE_ROTATION,
  ROTATING,
  CALCULATE_ROTATION_CORRECTION,
  ROTATE_TO_TARGET,
  RAISE_AND_DROP_SHOOTER_INIT,
  DROP_SHOOTER,
  RAISE_SHOOTER,
  SHOOTING_INIT,
  SHOOTING,
  DONE;
}
